# Generated by Django 2.2.2 on 2019-06-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.IntegerField()),
                ('receiver', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('seen', models.BooleanField(default=False)),
                ('del_by_sender', models.BooleanField(default=False)),
                ('del_by_receiver', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
            ],
        ),
    ]
