# Generated by Django 2.2.2 on 2019-06-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='del_by_receiver',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='del_by_sender',
            field=models.IntegerField(default=0),
        ),
    ]
