# Generated by Django 2.2.3 on 2019-07-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20190619_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.IntegerField()),
                ('receiver', models.IntegerField()),
                ('seen', models.BooleanField(default=False)),
            ],
        ),
    ]
