# Generated by Django 2.2.2 on 2019-06-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='topic',
        ),
    ]
