# Generated by Django 2.2.2 on 2019-06-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(default='/profile/', max_length=200),
        ),
    ]
