# Generated by Django 2.2.3 on 2019-07-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_notification_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
