# Generated by Django 2.2.3 on 2019-07-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_like_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='is_liked',
        ),
    ]
