# Generated by Django 3.0.2 on 2020-09-04 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0009_remove_like_is_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='storytype',
            field=models.TextField(default=' added a story '),
        ),
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.CharField(default='loadMyProfile()', max_length=200),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='post-images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Post')),
            ],
        ),
        migrations.CreateModel(
            name='PostForUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
