# Generated by Django 2.1 on 2020-11-30 16:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_auto_20200904_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='url',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
