# Generated by Django 2.1 on 2020-11-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_auto_20201130_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='url',
            field=models.ImageField(upload_to='post-images/'),
        ),
    ]
