# Generated by Django 2.2.3 on 2019-07-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0003_auto_20190724_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(upload_to='user-profile/'),
        ),
    ]
