# Generated by Django 2.2.3 on 2019-07-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0004_auto_20190724_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='user-profile/'),
        ),
    ]
