# Generated by Django 2.2.3 on 2019-07-24 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0005_auto_20190724_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField( upload_to='user-profile/'),
            preserve_default=False,
        ),
    ]
