# Generated by Django 2.2.3 on 2019-07-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0007_auto_20190724_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default_pp.png', upload_to='user-profile/'),
        ),
    ]
