# Generated by Django 2.1 on 2020-11-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0008_auto_20190725_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='avatar.svg', upload_to='user-profile/'),
        ),
    ]
