# Generated by Django 2.1 on 2020-11-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0009_auto_20201130_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default_pp.png', upload_to='user-profile/'),
        ),
    ]
