# Generated by Django 2.1 on 2020-11-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friends', '0010_auto_20201130_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='avatar.svg', upload_to='user-profile/'),
        ),
    ]
